version: "3"
services:
  frontend:
    container_name: frontend
    build: 
      context: ./frontend
    ports:
      - 80:80
    networks:
      - client-side
  base_api:
    build: ./backend_services
    container_name: base_api
    networks:
      - backend-apis
  api_gateway:
    build: ./backend_services/api_gateway
    container_name: api_gateway
    networks:
      - client-side
      - backend-apis
    ports:
      - 8000:8000
    environment:
      - USERS_SERVICE_HOST=users_api
      - SESSIONS_SERVICE_HOST=sessions_api
      - QUESTIONS_SERVICE_HOST=questions_api
      - MATCHING_SERVICE_HOST=matching_api
  users_api:
    build: ./backend_services/users_service/api
    container_name: users_api
    ports: 8000:8000
    networks:
      - backend_apis
      - users-data
    environment:
      - POSTGRES_HOST=users_database
      - POSTGRES_PORT=5432
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      - users_database
  questions_api:
    build: ./backend_services/questions_service/api
    container_name: questions_api
    ports: 8000:8000
    networks:
      - backend_apis
      - questions-data
    environment:
      - POSTGRES_HOST=questions_database
      - POSTGRES_PORT=5432
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      - questions_database
  users_database:
    build: ./backend_services/users_service/database
    container_name: users_database
    ports:
      - 5432:5432
    networks:
      - users-data:
    volumes:
      - sql-data:/var/lib/postgresql
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=${PGDATA}
  questions_database:
    build: ./backend_services/questions_service/database
    container_name: questions_database
    ports:
      - 5432:5432
    networks:
      - server-side
    volumes:
      - sql-data:/var/lib/postgresql
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=${PGDATA}
volumes:
  sql-data:
    external: true
networks:
  users-data:
  questions-data:
  client-side:
  backend-apis: