version: "3"
services:
  frontend:
    container_name: frontend
    build: 
      context: ./frontend
    ports:
      - 80:80
    networks:
      - client-side
  api:
    build: ./api
    container_name: api
    networks:
      - server-side
      - client-side
    ports:
      - 8000:8000
    environment:
      - POSTGRES_HOST=database
      - POSTGRES_PORT=3306
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  database:
    build: ./database
    container_name: database
    ports:
      - 5432:5432
    networks:
      - server-side
    volumes:
      - sql-data:/var/lib/postgresql
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=${PGDATA}
volumes:
  sql-data:
    external: true
networks:
  client-side:
  server-side: