# Needs to be version 2.4 to use:
#   depends_on:
#     condition:
version: '2.4'

x-logging:
  &default-logging
  logging:
    driver: json-file
    options:
      max-size: 100m

services:
  judge0_server:
    container_name: judge0_server
    image: judge0/judge0:1.13.0
    volumes:
      - ./judge0.conf:/judge0.conf:ro
    privileged: true
    depends_on:
      judge0_workers:
        condition: service_started
      judge0_db:
        condition: service_healthy
      judge0_redis:
        condition: service_healthy
    <<: *default-logging
    restart: always
    networks:
      - judge0

  judge0_workers:
    container_name: judge0_workers
    image: judge0/judge0:1.13.0
    command: ["./scripts/workers"]
    volumes:
      - ./judge0.conf:/judge0.conf:ro
    privileged: true
    depends_on:
      judge0_db:
        condition: service_healthy
      judge0_redis:
        condition: service_healthy
    <<: *default-logging
    restart: always
    networks:
      - judge0

  judge0_db:
    container_name: judge0_db
    image: postgres:13.0
    env_file: judge0.conf
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 2s
      timeout: 5s
      retries: 10
    <<: *default-logging
    restart: always
    networks:
      - judge0

  judge0_redis:
    container_name: judge0_redis
    image: redis:6.0
    command: [
      "bash", "-c",
      'docker-entrypoint.sh --appendonly yes --requirepass "$$REDIS_PASSWORD"'
    ]
    env_file: judge0.conf
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping || exit 1"]
      interval: 2s
      timeout: 5s
      retries: 10
    <<: *default-logging
    restart: always
    networks:
      - judge0

volumes:
  postgres-data:
  redis-data:

networks:
  judge0:
