version: "3"

services:
  api_gateway:
    container_name: api_gateway
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx_params_handle_websockets:/etc/nginx/nginx_params_handle_websockets:ro
      - nginx_logs:/var/log/nginx
    depends_on:
      - users_api
      - questions_api
      - matching_api
      - collaboration_api
      - communication_api
      - code_execution_api
    networks:
      - client-side
      - backend-apis

volumes:
  nginx_logs:
